services:
  ymsDatabase:
    container_name: ymsDatabase
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=M@xY7#zQ2!pVw8&d
    restart: always
    ports:
      - "1429:1436"
  wmsDatabase:
    container_name: wmsDatabase
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=9g*T$L1x#R@oN3vK
    restart: always
    ports:
      - "1431:1434"
  sapDatabase:
    container_name: sapDatabase
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Z@5pB!wY8*mQ7#X2
    restart: always
    ports:
      - "1430:1435"  