services:
  ymsDatabase:
    image: mcr.microsoft.com/mssql/server
  wmsDatabase:
    image: mcr.microsoft.com/mssql/server
  sapDatabase:
    image: mcr.microsoft.com/mssql/server
volumes:
  yms_data:
  wms_data:
  sap_data:

